---
title: "Coleta e Classificação de Discursos do Senado Federal utilizando Agent AI"
author:
  - Ana Beatriz
  - Alberto Bastos
  - Victor Caetano
output:
  pdf_document:
    keep_tex: true
    number_sections: true
    fig_caption: true
    toc: true
    toc_depth: 5
    includes:
      in-header: preambulo.tex
      # before_body: newpage.tex
  html_document: default
date: "2025-05-14"
---

\begin{abstract}
Este é o resumo do artigo. Deve conter uma breve descrição dos objetivos, métodos, resultados e conclusões. Máximo de 250 palavras.
\end{abstract}

\textbf{Palavras-chave:} palavra1; palavra2; palavra3

\section{Introdução}
Contextualização do problema, lacunas na literatura, objetivos.

\section{Trabalhos Relacionados}
Discussão de estudos anteriores relevantes, comparando abordagens, lacunas e contribuições.

\section{Metodologia}
Descrição clara e replicável dos métodos utilizados, incluindo materiais, ferramentas e processos.

\section{Resultados}
Apresentação dos dados e análise estatística ou qualitativa.

\section{Discussão}
Interpretação dos resultados, relação com hipóteses, implicações teóricas ou práticas.

\subsection{Ameaças à Validade}
Discussão das possíveis limitações do estudo quanto à validade interna, externa, de construção e de conclusão.

\subsection{Trabalhos Futuros}
\colorbox{yellow}{Futuramente outras implementações podem ser feitas no código, de modo a permitir que funcionalidade, após interação com usuário, sugira temas.}


\section{Conclusão}
Resumo dos principais achados, contribuições e encerramento do artigo.

\section*{Agradecimentos}
(Se aplicável)

\bibliographystyle{apalike}
\bibliography{referencias}

\appendix
\section*{Apêndice}
(Material suplementar, se necessário)

\end{document}